"""last_seen_msg now default = 0

Revision ID: 2078ca0c06fb
Revises: 7a25ce1a00e6
Create Date: 2025-12-03 11:56:16.195676

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2078ca0c06fb"
down_revision: Union[str, Sequence[str], None] = "7a25ce1a00e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
