"""removed enum

Revision ID: 25e76ca40f5d
Revises: 00ecd3faa73d
Create Date: 2025-11-29 16:02:02.178690

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25e76ca40f5d"
down_revision: Union[str, Sequence[str], None] = "00ecd3faa73d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "messages",
        "status",
        existing_type=postgresql.ENUM("pending", "delivered", name="message_status"),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "messages",
        "status",
        existing_type=sa.String(),
        type_=postgresql.ENUM("pending", "delivered", name="message_status"),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
