"""add presence_status and last_seen column in the User table

Revision ID: 3fe06f7b84db
Revises: 4cd67f723870
Create Date: 2025-11-28 16:43:19.346931

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3fe06f7b84db"
down_revision: Union[str, Sequence[str], None] = "4cd67f723870"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("presence_status", sa.String(), nullable=True))
    op.add_column("users", sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_seen")
    op.drop_column("users", "presence_status")
    # ### end Alembic commands ###
