"""add status column

Revision ID: 54a529f4437a
Revises: d4d826bcd1a2
Create Date: 2025-11-27 15:25:19.375278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = '54a529f4437a'
down_revision: Union[str, Sequence[str], None] = 'd4d826bcd1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    message_status = ENUM('pending', 'delivered', name='message_status')
    message_status.create(op.get_bind(), checkfirst=True)
    op.add_column('messages', sa.Column('status', message_status, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'status')
    message_status = ENUM('pending', 'delivered', name='message_status')
    message_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
