"""message column accepts null and add column last_read_msg_id

Revision ID: 7a25ce1a00e6
Revises: 7ab6e0071ba4
Create Date: 2025-12-03 10:28:54.765456

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a25ce1a00e6"
down_revision: Union[str, Sequence[str], None] = "7ab6e0071ba4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("group_members", sa.Column("last_read_message_id", sa.Integer(), nullable=True))
    op.alter_column("group_messages", "message", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("messages", "message", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("messages", "message", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("group_messages", "message", existing_type=sa.TEXT(), nullable=False)
    op.drop_column("group_members", "last_read_message_id")
    # ### end Alembic commands ###
