"""add author and group relationship to GroupMessage

Revision ID: c9fe8916d7c6
Revises: 2078ca0c06fb
Create Date: 2025-12-05 18:04:05.022981

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9fe8916d7c6"
down_revision: Union[str, Sequence[str], None] = "2078ca0c06fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
